### ISSUE TITLE
Consistent Color/Colour naming

### ISSUE THREAD

**Issue by sharpner** [gazed/vu#3]
Hi! 
awesome library thanks for the hard work so far! 
I just started using it but I already fell in love :-)

But it would awesome if color would be named consistently within the library (preferably color :P).

In vu.Eng#SetColor its SetColor but in
render.Light its SetColour/GetColour(). 

Thx!

**Comment by gazed** [comment]
Thank you for trying vu and taking the time to provide feedback.

I’ve made the change as you recommend and standardized on color throughout.
The change is in the internal galvanized logic repo and it will appear next time the internal repo is released to github.

rust

**Comment by sharpner** [comment]
awesome! thank you

**Comment by sharpner** [comment]
yay =)
